name: todo_list_app_flutter
description: A to do list App Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #beatiful navbar from google
  google_nav_bar: ^5.0.6

  #state management
  flutter_bloc: ^8.1.3

  #database local
  floor: ^1.4.2

  #comparing dart objects
  equatable: ^2.0.5

  #beautiful style
  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor

  #Date Format
  intl: ^0.18.1

  #service locator
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: MuseoSans100
      fonts:
        - asset: lib/config/fonts/museo_sans100.ttf
        - asset: lib/config/fonts/museo_sans100italic.ttf
          style: italic
    - family: MuseoSans300
      fonts:
        - asset: lib/config/fonts/museo_sans300.ttf
        - asset: lib/config/fonts/museo_sans300italic.ttf
          style: italic
    - family: MuseoSans500
      fonts:
        - asset: lib/config/fonts/museo_sans500.ttf
        - asset: lib/config/fonts/museo_sans500italic.ttf
          style: italic
    - family: MuseoSans700
      fonts:
        - asset: lib/config/fonts/museo_sans700.ttf
        - asset: lib/config/fonts/museo_sans700italic.ttf
          style: italic
    - family: MuseoSans900
      fonts:
        - asset: lib/config/fonts/museo_sans900.ttf
        - asset: lib/config/fonts/museo_sans900italic.ttf
          style: italic
