name: todo_list_app_flutter
description: A to do list App Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #beatiful navbar from google
  google_nav_bar: ^5.0.6

  #state management
  flutter_bloc: ^8.1.3

  #database local
  floor: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner:

flutter:
  uses-material-design: true
